<?php


/*
|--------------------------------------------------------------------------
| R/a/dio Database Schema
|--------------------------------------------------------------------------
|
| Once this is live, DO NOT EDIT THIS FILE. CREATE A MIGRATION.
| This is the base skeleton for R/a/dio's database.
| Models probably wont be added due to the complexity of the database.
|
| This works on every database PDO supports, not just mysql (I assume)
|
*/

/**
 * Users table - central point for a bunch o' keys
 *
 * Creates the table.
 */
Schema::create('users', function($table) {
	$table->increments('id')->unsigned();
	$table->string('user')->unique();
	$table->string('pass');
	$table->integer('privileges')->unsigned()->default(0);
});


/**
 * DJs table
 *
 * Creates the table.
 */
Schema::create('djs', function($table) {
	$table->increments('id')->unsigned();
	$table->integer('user_id')->

});